#!/usr/bin/env node

// Declaration hoisting lifts the declarations within functions to the top of the function.
// The assignment is NOT lifted with the declaration.

var myHealth = 100;
 
var decrementHealth = function() {
    console.log(myHealth);
     
    var myHealth = myHealth - 1;
};
 
decrementHealth();

// Equivalent code that is generated by the Javascript engine:

var myHealth = 100;
 
var decrementHealth = function() {
    var myHealth;
    console.log(myHealth);
     
    myHealth = myHealth-1;
};

decrementHealth()

// Correct code to use is:

var myHealth = 100;
 
var decrementHealth = function(health) {
    var myHealth = health;
    myHealth--;
    console.log(myHealth);
};
 
decrementHealth(myHealth);
console.log(myHealth);